version: '3'

services:
  back:
    container_name: back
    restart: always
    image: codelande/devmanager_prod_back:latest
    command:
      - /bin/sh
      - -c
      - |
        npx typeorm migration:run -d /app/apps/backend/api/dist/src/config/migration.config.js
        node /app/apps/backend/api/dist/src/main.js
    depends_on:
      - mysql
    environment:
      - NODE_ENV=production
    env_file:
      - ./back.env

  front:
    container_name: front
    image: codelande/devmanager_prod_front:latest
    volumes:
      - frontend:/app
    environment:
      - NODE_ENV=production

  mysql:
    container_name: mysql-devmanager
    image: mysql:8.0.31
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - ./mysql.env
    volumes:
      - ./db:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    depends_on:
      - back
      - front
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
      - frontend:/frontend

volumes:
  frontend:
